[settings]
timeout = 1000

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  args = ["-lruntime=debug,parachain=trace" ]

  [[relaychain.nodes]]
  name = "bob"
  args = ["-lruntime=debug,parachain=trace" ]

  [[relaychain.nodes]]
  name = "charlie"
  args = ["-lruntime=debug,parachain=trace" ]

[[parachains]]
id = 1005
chain = "coretime-rococo-local"

  [parachains.collator]
  name = "coretime-collator"
  image = "{{COL_IMAGE}}"
  command = "polkadot-parachain"
  args = [ "-lruntime=debug,parachain=trace" ]

[[parachains]]
id = 100
add_to_genesis = false
register_para = false
onboard_as_parachain = false
cumulus_based = true

  [parachains.collator]
  name = "collator01"
  image = "{{CUMULUS_IMAGE}}"
  command = "polkadot-parachain"
